/*
 * generated by Xtext 2.13.0
 */
package org.example.fj.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.example.fj.fj.FJProgram
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FJInjectorProvider)
class FJParsingTest {
	@Inject
	ParseHelper<FJProgram> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			class Object {
				
			}
			
			class Pair extends Object {
				private Object fst;
				private Object snd;
				
				public Object getFst() {
					return this.fst;
				}
				public Object getSnd() {
					return this.snd;
				}
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
