/*
 * generated by Xtext 2.13.0
 */
package org.example.expressions.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ExpressionsUiModule extends AbstractExpressionsUiModule {
}
