/*
 * generated by Xtext 2.14.0
 */
package org.example.expressions.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ExpressionsWebModule extends AbstractExpressionsWebModule {
}
