<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.expressions</string>
	</array>
	<key>name</key>
	<string>expressions</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.control.expressions</string>
			<key>match</key>
			<string>\b(eval|false|true|var)\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.expressions</string>
</dict>
</plist>
