/*
 * generated by Xtext 2.13.0
 */
package org.example.fj


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FJRuntimeModule extends AbstractFJRuntimeModule {
}
