/*
 * generated by Xtext 2.13.0
 */
package org.example.fj


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FJStandaloneSetup extends FJStandaloneSetupGenerated {

	def static void doSetup() {
		new FJStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
