/*
 * generated by Xtext 2.13.0
 */
package org.example.fj.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.example.fj.FJRuntimeModule
import org.example.fj.FJStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FJIdeSetup extends FJStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FJRuntimeModule, new FJIdeModule))
	}
	
}
